export const SIGNUP_SUCESS = "SIGNUP_SUCESS";
export const SIGNUP_ERROR = "SIGNUP_ERROR";

export const SIGNIN_SUCESS = "SIGNIN_SUCESS";
export const SIGNIN_ERROR = "SIGNIN_ERROR";

export const SIGNOUT_SUCESS = "SIGNOUT_SUCESS";
export const SIGNOUT_ERROR = "SIGNOUT_ERROR";